version: "3.7"
services:

  epic-games-claimer:
    image: ech0sec/awesome-epic:fish
    init: true
    command: "python3 claim.py"
    volumes:
      - "/home/epic/user_data_dir:/home/epic/user_data_dir"
      - "/home/epic/logs:/home/epic/logs"
    environment:
      EPIC_EMAIL: jw199875@qq.com
      EPIC_PASSWORD: aiziji520...

# ======================================
# [🍜] Documentaion
# ======================================
# docker-compose https://docs.docker.com/compose/reference/
# apprise https://github.com/caronc/apprise
